# destination: site_staging

# Site settings
title:  AI Consultant and Educator
SEOTitle: Sheng's Blog | BY GS
header-img: image/rawa-sun-falling2-a
email: goseng123@gmail.com
description:  积少成多，集腋成裘
keyword: "高升的博客, 高升，gaosheng, 机器学习，人工智能, AI, machine learning, speech recognition, nlp, data science "
url: "http://aigaosheng.github.io"          
github_repo: "https://github.com/aigaosheng/aigaosheng.github.io.git"

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: AI/ML researcher and developer. Data science. Ads optimizer for CTR, news recommendation
sidebar-avatar: /image/gs.jpg     


# SNS settings
RSS: false
linkedin_username:    dlsheng 
github_username:    aigaosheng


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "draft", "docs", "img", "search.json"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

defaults:
  - scope:
      path: ""
      type: "json"
    values:
      layout: null


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus（https://disqus.com/）
disqus_username: aigaosheng-github-io
disqus:
  enable: true    #是否开启Disqus评论
  username: aigaosheng-github-io

#Gitalk
#gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
#  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
#  repo: masterAIalgo.github.io    #仓库名称
#  owner: masterAIalgo    #github用户名
#  admin: masterAIalgo
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-148412725-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "",
        href: ""
    },
]
