# destination: site_staging
timezone: "Asia/Singapore"

# Site settings
title: Transform Your Business with AI | Consulting & Development
SEOTitle: AI Consultant | Machine Learning Solutions | Expert Developers
header-img: image/rawa-sun-falling2-a
email: goseng123@gmail.com
description:  积少成多，集腋成裘
keyword: AI Consultant, Machine Learning Solutions, Data Science Services, Expert Developers
url: "https://www.aisengtech.com"          
github_repo: "https://github.com/aigaosheng/aigaosheng.github.io.git"

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: Artificial intelligence, Agent, machine learning, data science, Expert Developers
sidebar-avatar: /image/gs.jpg     

# SNS settings
RSS: false
linkedin_username:    dlsheng 
github_username:    aigaosheng


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 60
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "draft", "docs", "img"]
anchorjs: true 



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus（https://disqus.com/）
# disqus_username: aigaosheng-github-io
# disqus:
#   enable: False    #是否开启Disqus评论
#   username: aigaosheng-github-io

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends
friends: [
    {
        title: "",
        href: ""
    },
]
